version: 2

sources:
  - name: state_market_deals
    schema: main
    config:
      plugin: state_market_deals
      save_mode: ignore
    tables:
      - name: active_miners
        config:
          table: active_miners_v2
