version: 2

sources:
  - name: raw_assets
    schema: raw
    tables:
      - name: raw_storage_providers_daily_power
        meta:
          dagster:
            asset_key: ["raw_storage_providers_daily_power"]
      - name: raw_datacapstats_verified_clients
        meta:
          dagster:
            asset_key: ["raw_datacapstats_verified_clients"]
      - name: raw_filecoin_state_market_deals
        meta:
          dagster:
            asset_key: ["raw_filecoin_state_market_deals"]
      - name: raw_storage_providers_location_provider_quest
        meta:
          dagster:
            asset_key: ["raw_storage_providers_location_provider_quest"]
      - name: raw_storage_providers_filrep_reputation
        meta:
          dagster:
            asset_key: ["raw_storage_providers_filrep_reputation"]
      - name: raw_verified_registry_verifiers
        meta:
          dagster:
            asset_key: ["raw_verified_registry_verifiers"]
      - name: raw_datacapstats_verifiers
        meta:
          dagster:
            asset_key: ["raw_datacapstats_verifiers"]
      - name: raw_storage_providers_token_balances
        meta:
          dagster:
            asset_key: ["raw_storage_providers_token_balances"]
      - name: raw_storage_providers_rewards
        meta:
          dagster:
            asset_key: ["raw_storage_providers_rewards"]
      - name: raw_spark_retrieval_success_rate
        meta:
          dagster:
            asset_key: ["raw_spark_retrieval_success_rate"]
