project:
  type: website
  output-dir: .quarto/_site
  preview:
    port: 4200

execute:
  freeze: true
  cache: true

title-block-banner: true

website:
  title: "Filecoin Analytics"
  navbar:
    right:
      - icon: github
        href: https://github.com/davidgasquez/filecoin-analytics
      - icon: twitter
        href: https://twitter.com/davidgasquez/

format:
  html:
    code-fold: true
