project:
  type: website
  output-dir: .quarto/_site
  preview:
    port: 4200

website:
  title: "Filecoin Analytics"
  repo-url: https://github.com/davidgasquez/filecoin-analytics
  repo-actions: [edit, issue]
  search: false
  page-footer:
    center: "David Gasquez"
  navbar:
    logo: "https://www.pngall.com/wp-content/uploads/10/Filecoin-Crypto-Logo-180x180.png"
    search: false
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez/
      - icon: github
        href: https://github.com/davidgasquez/filecoin-analytics

  # sidebar:
  #   contents: auto

format:
  html:
    code-fold: true
    # theme: lux
    # css: "custom.css"
