[project]
name = "fdp"
version = "0.1.0"
dependencies = [
    "altair",
    "dbt-core",
    "dbt-duckdb",
    "dagster",
    # "dagster-webserver",
    "dagster-dbt",
    "dagster-duckdb-pandas",
    "duckdb",
    "ijson",
    "ipykernel",
    "ipywidgets",
    "jupysql",
    "jupyterlab",
    "matplotlib",
    # "nbclient",
    "nbformat",
    # "numpy",
    "pandas",
    "pyarrow",
    "regex",
    "tqdm",
    "toml",
    "zstandard",
]
requires-python = ">=3.10, <3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["dagit", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fdp"]
