name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/davidgasquez/fdp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run:
    name: Run
    runs-on: ubuntu-latest
    needs: build
    # container:
    #   image: ghcr.io/davidgasquez/fdp:latest
    #   env:
    #     SPACESCOPE_TOKEN: ${{ secrets.SPACESCOPE_TOKEN }}
    #   volumes:
    #     - ./:/workspaces/filecoin-data-portal/
    steps:
        - name: Free Disk Space
          uses: jlumbroso/free-disk-space@main
          with:
            tool-cache: true
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true
        - name: Maximize build space
          uses: easimon/maximize-build-space@master
          with:
            remove-dotnet: 'true'
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run DAG
          run: docker run -t -e SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }} -v $PWD/:/workspaces/filecoin-data-portal/ ghcr.io/davidgasquez/fdp:latest pip install -e . && make run
        - name: Render Quarto
          run: docker run -t -e SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }} -v $PWD/:/workspaces/filecoin-data-portal/ ghcr.io/davidgasquez/fdp:latest make render
        - name: Publish Docs
          uses: JamesIves/github-pages-deploy-action@4.0.0
          with:
            branch: gh-pages
            folder: .portal/quarto/_site
