name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        run: docker build -t davidgasquez/fdp:latest . --build-arg SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }} --build-arg STATEMARKETDEALS_POSTGRES_URI=${{ secrets.STATEMARKETDEALS_POSTGRES_URI }}
      - name: Run dbt
        run: docker run -t -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make run
      - name: Render Quarto
        run: docker run -t -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make publish



# name: CI

# on:
# push:
# branches:
#     - main

# jobs:
# build:
# name: Build
# runs-on: ubuntu-latest
# steps:
#     - name: Checkout
#     uses: actions/checkout@v2
#     - name: Build Docker
#     run: docker build -t davidgasquez/fdp:latest .

# run:
# name: Run
# runs-on: ubuntu-latest
# needs: build
# container:
#     image: davidgasquez/fdp:latest
#     env:
#         SPACESCOPE_TOKEN: ${{ secrets.SPACESCOPE_TOKEN }}
#         STATEMARKETDEALS_POSTGRES_URI: ${{ secrets.STATEMARKETDEALS_POSTGRES_URI }}
# steps:
#     - name: Checkout
#     uses: actions/checkout@v2
#     - name: Run
#     run: make run
