name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and Push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: ghcr.io/davidgasquez/fdp:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

  run:
    name: Run
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/davidgasquez/fdp:latest
    #   env:
    #     SPACESCOPE_TOKEN: ${{ secrets.SPACESCOPE_TOKEN }}
    #   volumes:
    #     - ./:/workspaces/filecoin-data-portal/
    steps:
        # - name: Free Disk Space
        #   uses: jlumbroso/free-disk-space@main
        #   with:
        #     tool-cache: true
        #     android: true
        #     dotnet: true
        #     haskell: true
        #     large-packages: true
        #     docker-images: true
        #     swap-storage: true
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            pip install -e .
