name: CI

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Publish 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        run: docker build -t davidgasquez/fdp:latest .
      - name: Run dbt
        run: docker run -t -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make run
      - name: Render Quarto
        run: docker run -t -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make publish
    #   - name: Publish Docs
    #     uses: JamesIves/github-pages-deploy-action@4.0.0
    #     with:
    #       branch: gh-pages
    #       folder: .quarto/output
